image:
  file: .gitpod.Dockerfile
tasks:
  - command: |
      gp ports await 26000
      gp preview $(gp url 26000)?folder=/workspaces/vscode-remote-try-java --external
    name: Preview
  - command: |
      git clone https://github.com/akosyakov/vscode-remote-try-java /workspace/vscode-remote-try-java && true
      ./start.sh
    name: Run Dev Container

  